### ISSUE TITLE
App doesn't colorize controls if the scaling is more than 125%

### ISSUE THREAD

**Issue by rounk-ctrl** [krlvm/AccentColorizer#1]
I think opening the theme data with [OpenThemeDataForDpi](https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-openthemedatafordpi) would work.

**Comment by krlvm** [comment]
This is a very big problem, last time it could not be fixed, even with OpenThemeDataForDpi

https://github.com/valinet/ExplorerPatcher/discussions/436

**Comment by krlvm** [comment]
Also checked on 1709 and can't reproduce, I'm pretty sure this should be definitely bugged though, because the most of classes have different bitmaps per DPI value.
Can you provide details?

**Comment by krlvm** [comment]
Windows 11 RP / Beta (Build 22621), 175% and 175% set as custom scale factor

The only thing I noticed, that after I rolled back to my preferred 125%, everything became blue, but after I restarted the application, everything became green again

![1](https://user-images.githubusercontent.com/51774833/173130565-1914d1c9-4c11-4120-891d-ba0df7223ea6.png)
![2](https://user-images.githubusercontent.com/51774833/173130567-7f2cc589-583a-4450-bc76-3bbbe42def4b.png)

**Comment by rounk-ctrl** [comment]
oh but shouldn't the app automatically do it tho
as it is running in the background
ig respond to `WM_DPICHANGED` message

**Comment by krlvm** [comment]
Didn't think about it.
So everything worked for you after the restart?
If yes, then I'm pleasantly surprised, because for some reason it caused problems last time.

**Comment by krlvm** [comment]
I wonder if this will all work with two monitors with different DPI each.

**Comment by rounk-ctrl** [comment]
> Didn't think about it. So everything worked for you after the restart? If yes, then I'm pleasantly surprised, because for some reason it caused problems last time.

yea

**Comment by krlvm** [comment]
Very glad to hear!

**Comment by rounk-ctrl** [comment]
Also shouldn't a tray icon be ideal? I mean it runs in the background anyways.

**Comment by krlvm** [comment]
Initially, I wanted to make a small program that just runs in the background and does not show any signs of life, although there is a room for improvements: a tray icon, a window for choosing colors - if you are interested in this, you can create a new project based on this - I need just figure out how to extract the main code from here so that it can be updated independently of the UI as a git submodule.

**Comment by rounk-ctrl** [comment]
Ok
