### ISSUE TITLE
[Win7] Colorization gets lost after shutdown or restart with latest accentcolorizer version

### ISSUE THREAD

**Issue by MasterSlenderTR** [krlvm/AccentColorizer#11]
The final accentcolorizer version where this bug doesn't exist is v1.1.14 which I'm stuck with it right now.

**Comment by krlvm** [comment]
Does not work indeed.
Thanks for reporting.

**Comment by krlvm** [comment]
Resolved in [v1.1.18](https://github.com/krlvm/AccentColorizer/releases/tag/v1.1.18)
