### ISSUE TITLE
some parts in explorer not being colored

### ISSUE THREAD

**Issue by fawzynahwi** [krlvm/AccentColorizer#12]
hey! after installing almost everything was colored except for the selection in file explorer even though the pictures you provided it shows them colored.
![image](https://user-images.githubusercontent.com/52822428/188770155-1f7d129f-d483-46bc-83dc-61c99b04f2b3.png)

**Comment by krlvm** [comment]
It colorizes only that elements, that is colored, usually with blue. Selection highlight are grey - this is intended design choice by Microsoft to ensure there's enough contrast with background, so it should not be colorized.
