### ISSUE TITLE
this is bad. this is really really bad for me. he tinted ui red.

### ISSUE THREAD

**Issue by MuscularPuky** [krlvm/AccentColorizer#13]
something is definitely wrong. accent applicator worked great but accent colorzer dyed my ui color RED like bf1818, d40000. where is config? where is restre to default? even winpallette cant undo this corrupted color. swear, i never used red accent color since install windows. if you cant help about this problem, teach me how this app works, please. ill revert it manually via regedit.

P.S. E11 works but how to restore to default? he brought disappointing result.

**Comment by krlvm** [comment]
All changes can be reverted by picking Default Blue color in personalization settings and killing AccentColorizer then. Same applies to AccentColorizer-E11.

I think it uses the red color because your accent color hue is too low. That's how RGB<->HSV colors math work.

**Comment by MuscularPuky** [comment]
oh is it background service, not patcher? phew- sorry about snapped at you. i thought it would modify system. i am really sorry. i got some hint from your answer. i think i can get accet color what i want wth little system modifying.

**Comment by krlvm** [comment]
Yes. It is clearly stated that it does not modify system files and changes can be reverted by reboot.
