### ISSUE TITLE
AccentColorizer colors are too bright compared to WinUI elements

### ISSUE THREAD

**Issue by Diegorro98** [krlvm/AccentColorizer#14]
I've found that the selections are too bright. At least for the color that I have as accent color.

Selected Accent Color in settings (HEX 338582):
![Selected Accent Color (HEX 338582)](https://user-images.githubusercontent.com/22046575/192823389-46568e9a-4743-49ea-af87-b9a2c5f0d0e6.png)

AccentColorizer Selection (HEX 48d1c9):
![AccentColorizer Selection (HEX 48d1c9)](https://user-images.githubusercontent.com/22046575/192823836-ca27ecc9-74e4-4f3f-8d21-25c19417a9fb.png)

WinUI Selection (Same HEX than selected in settings):
![WinUI Selection](https://user-images.githubusercontent.com/22046575/192824081-53b0ae30-c02f-4872-94c4-fe268f3222ea.png)

This makes colors inconsistent with other colors on Windows.

**Comment by krlvm** [comment]
I think that happens because the original blue highlight color is too bright compared to WinUI, is not it?

**Comment by Diegorro98** [comment]
Well, the original blue highlight color can't be compared to WinUI because it is not set by WinUI, I mean is a default color that is static.
But selection is just an example, we could use other examples, like progress bars:

WinUI progressbar (HEX same than selected accent color in the last comment):
![WinUI Progressbar](https://user-images.githubusercontent.com/22046575/192972163-aec66030-10ca-4465-8023-ac689833fb98.png)


Copy dialog progress bar (HEX 05B0A7)
![AccentColor Progressbar](https://user-images.githubusercontent.com/22046575/192972743-a7c99023-4f17-420e-85bf-01930ffc44f2.png)

**Comment by krlvm** [comment]
AccentColorizer just changes the tint of theme colors (HSV's hue), so it's highly depends on the original colors.

It's not just my choice to make everything so light, unfortunately.

**Comment by Diegorro98** [comment]
Okey, that's good to know
Thank you for this cool software!
