### ISSUE TITLE
Doesn't colorize the save/open with dialog box

### ISSUE THREAD

**Issue by Vipin2003** [krlvm/AccentColorizer#15]
1. There is a issue or bug that it doesn't colorize the address bar (menu appear after clicking the drop down arrow). It colorize the address bar but not the drop-down menu. Same this also doesn't work in save/open with dialog boxes. And the text box (where we type the name of file to be saved) drop-down menu also doesn't colorize. They always be blue.
2. The progress bar of copy/paste dialog box doesn't matches the accent color when clicked on "show more" button. The detailed progress bar (where progress goes like the heart rate machine ). It always be green.

Please fix these issues in next update.

**Comment by krlvm** [comment]
1. Unfortunately, save/open dialogs dropdown menu does not use theme colors, so I can't fix it, unfortunately
2. Copy/paste dialogs graphs are drawn with color values being used instead of bitmaps, so, again, I can't fix it - a custom theme is needed to do it (#9)

**Comment by krlvm** [comment]
As I said before, it is not possible.
It's not that I don't want to or I'm too lazy, it's simply impossible, unfortunately.
