### ISSUE TITLE
No progress bar colorization (registry key applied)

### ISSUE THREAD

**Issue by KernelFox0** [krlvm/AccentColorizer#19]
![Screenshot_20221226_090354](https://user-images.githubusercontent.com/65031582/209580343-9c545aa9-4db6-4e63-bac2-c694d08e1538.png)
![image](https://user-images.githubusercontent.com/65031582/209580405-6dca62df-430e-4040-abee-15607b284e97.png)

**Comment by krlvm** [comment]
What's your Windows build?

**Comment by KernelFox0** [comment]
> What's your Windows build?

Windows 11 22H2, Build 22621.525

**Comment by KernelFox0** [comment]
> What's your Windows build?

Windows 11 22H2, Build 22621.525
(Sorry, accidentally closed issue, had to reopen)

**Comment by krlvm** [comment]
I see this is a custom theme, will it recolor if you pick red as the accent?

**Comment by KernelFox0** [comment]
> I see this is a custom theme, will it recolor if you pick red as the accent?

Nope. Stays blue.

**Comment by KernelFox0** [comment]
Any idea what might cause this?

**Comment by krlvm** [comment]
Can you test it with the default theme?
Can't reproduce on build 22621.

**Comment by Vipin2003** [comment]
> ![Screenshot_20221226_090354](https://user-images.githubusercontent.com/65031582/209580343-9c545aa9-4db6-4e63-bac2-c694d08e1538.png) ![image](https://user-images.githubusercontent.com/65031582/209580405-6dca62df-430e-4040-abee-15607b284e97.png)

How you get this blue color...are you using rectify11

**Comment by KernelFox0** [comment]
> How you get this blue color...are you using rectify11

Yes I do use Rectify11

**Comment by M7MDE7EGAZY** [comment]
so  progress colorization is dead ?

**Comment by KernelFox0** [comment]
I found the solution. Rectify11 was causing it. Without it there are no problems.

**Comment by M7MDE7EGAZY** [comment]
actually i don't use rectify 11

**Comment by M7MDE7EGAZY** [comment]
but i don't use rectify 11 it doesn't work with stock & niivu themes

**Comment by krlvm** [comment]
> but i don't use rectify 11 it doesn't work with stock & niivu themes

Read carefully

https://github.com/krlvm/AccentColorizer#progress-bar-colorization
