### ISSUE TITLE
Windows 11 Start Menu Icon Colorization With Open Shell

### ISSUE THREAD

**Issue by StereoMadnessss** [krlvm/AccentColorizer#20]
One thing that sticks out is how the start menu icon is the same color and especially if you are trying to make your experience revolve around one color, it really sticks out and looks out of place. Normally the icon can’t be customized, but with Open Shell it can, making the experience a lot more consistent. This should only be activated when it detects that Open Shell is installed.

**Comment by krlvm** [comment]
I don't use OpenShell, so I'm not likely to implement it, it's more of an idea for a separate project.
