### ISSUE TITLE
Add Scrollbar colorization

### ISSUE THREAD

**Issue by OrthodoxWindows** [krlvm/AccentColorizer#22]
First of all, thank you very much for your wonderful program !

On the Aerolite visual style, the scrollbar is in color. I think this is also the case on Windows 7 and 8, but I'm not sure (except for the aerolite visual style on Windows 8, where it's sure). This is just the highlighted scrollbar. An example :

![seamonkey_NERTnUNc7w](https://user-images.githubusercontent.com/100134023/210156850-439fa967-aba4-4561-8a69-94aa091f8025.png)

So my request is about adding support for scrollbar colorization.

**Comment by OrthodoxWindows** [comment]
This also applies to scroll arrows :

![seamonkey_kPVxDYSU2t](https://user-images.githubusercontent.com/100134023/210157014-c6296d30-2ae3-45ff-ad7c-443c08096487.png)

All these elements are stored in the ScrollBar category (in MsstyleEditor).

**Comment by krlvm** [comment]
Implemented in [version 1.1.19](https://github.com/krlvm/AccentColorizer/releases/tag/v1.1.19).

**Comment by OrthodoxWindows** [comment]
Sorry for that, but in the latest version there is no difference, the scrollbar and scroll buttons are still blue.

**Comment by OrthodoxWindows** [comment]
This may be because this is only for Windows 7; the problem is that the scroll bar is also blue in the aerolite style (present in all Windows since Windows 8). Maybe add an option to enable/disable scrollbar colorization like loading strips; it is true that for the scrollbar of Aero 10/11 this is not consistent.

**Comment by krlvm** [comment]
You can recompile it with enabling features you need for older Windows versions

**Comment by OrthodoxWindows** [comment]
Sorry to revive the discussion, but how do I get this in Windows 10 (or 8 or 11) ?

**Comment by krlvm** [comment]
It's gray on Windows 10, isn't it?

**Comment by OrthodoxWindows** [comment]
If the Aero Lite theme is selected in Windows 8, 10 or 11, the scrollbar selection color is blue. My screenshots are taken from Windows 10.

**Comment by OrthodoxWindows** [comment]
The same issue was reported here : https://github.com/krlvm/AccentColorizer/issues/35

**Comment by krlvm** [comment]
Will check it later when I'm able to switch the theme, #35 seems to be more problematic though

**Comment by krlvm** [comment]
It would be enough to move [this](https://github.com/krlvm/AccentColorizer/blob/01b012c895082434925b4d3a6993c4699f98a5cf/AccentColorizer/StyleModifier.cpp#L294) loop out of the condition which checks for Windows < 8
