### ISSUE TITLE
[BUG] taskbar application progress color is not changed.

### ISSUE THREAD

**Issue by bigplayer-ai** [krlvm/AccentColorizer#24]
![image](https://user-images.githubusercontent.com/119108387/212405632-a9b4e7d6-d9c4-40df-9f5e-9b2bb301fc8f.png)
Hey,
When running accent colorizer it works fine for applications, but on progress application in taskbar it does not change its color (check the photo attached)

**Comment by krlvm** [comment]
AFAIK there's no way to modify it on Windows 10+
