### ISSUE TITLE
Colorize File explorer glyphs

### ISSUE THREAD

**Issue by rounk-ctrl** [krlvm/AccentColorizer#3]
They are just stored in `C:\Windows\SystemApps\MicrosoftWindows.Client.Core_cw5n1h2txyewy\FileExplorerExtensions\Assets\images\contrast-standard`
as svg files.
So it should be possible to make it follow the accent color

**Comment by krlvm** [comment]
Thanks for the idea, it remains to figure out how to incorporate this into the main project.
I have made a quick and dirty prototype, but it is currently slow at getting file access rights for some reason.

https://github.com/krlvm/AccentColorizer-E11

**Comment by krlvm** [comment]
Also published an artifact so it is possible to test it in a VM without need to build: https://github.com/krlvm/AccentColorizer-E11/releases/tag/v0.0.1

**Comment by rounk-ctrl** [comment]
Nice
