### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Vipin2003** [krlvm/AccentColorizer#30]
Is there any way to use the progress bar colorization for every progress bar except the disk capacity bar.??
like I want to colorize all the progress bar but not the disk capacity bar (it should always be blue) as the color is not optimized well to use it on disk capacity bar.

**Comment by krlvm** [comment]
You just need to comment this line out

https://github.com/krlvm/AccentColorizer/blob/01b012c895082434925b4d3a6993c4699f98a5cf/AccentColorizer/StyleModifier.cpp#L258

**Comment by Vipin2003** [comment]
I have changed it but how to implement it...like I downloaded the zip and changed the file but what after that.

**Comment by Vipin2003** [comment]
Done..what to do next

**Comment by krlvm** [comment]
The executable you produced will not colorize the disk capacity bar

**Comment by Vipin2003** [comment]
Thanks...Finally completed.
