### ISSUE TITLE
Enhancement to AccentColorizer

### ISSUE THREAD

**Issue by Vipin2003** [krlvm/AccentColorizer#32]
Accent Colorizer should also colorize the text and the icons. As an example, I'm showing it in Control Panel.

![image](https://user-images.githubusercontent.com/93650504/235429466-6bcf4a64-d0cc-405d-a8d5-1244d7ea58ab.png)

![image](https://user-images.githubusercontent.com/93650504/235429752-2e786be2-fdee-4930-ab53-d0fca1617c1c.png)

![image](https://user-images.githubusercontent.com/93650504/235430006-68dfcf30-38b6-4fad-bb43-ccb35fd2b12b.png)

I think that it is possible to colorize these also. It is also available on Win10 for your convinience. Please try to update the AC as it is a long time since it was updated. Add these in next update.

**Comment by krlvm** [comment]
It is not possible
