### ISSUE TITLE
Need to complete work with Address Bar Coloring

### ISSUE THREAD

**Issue by Vipin2003** [krlvm/AccentColorizer#33]
You also need to colorize the Address Bar color also. It works but if we use arrow keys to select items, it won't work. I think that windows have 2 different boxes for both mouse and keyboard use. Please fix this bro.

![2023-05-18_21h46_05](https://github.com/krlvm/AccentColorizer/assets/93650504/2741486b-2b02-4a8b-ad16-efda27b6db8d)

![2023-05-18_21h47_28](https://github.com/krlvm/AccentColorizer/assets/93650504/12e9ec43-44e0-4666-91a0-2bb8c0ea22a7)

I've made a Issue regarding this and you have implemented it. But you haven't implemented it completely and leave it half-way. Pease bro, complete it in next version.

**Comment by krlvm** [comment]
This is just not technicially possible

**Comment by krlvm** [comment]
This is colorized though, at least on Windows 10
![image](https://github.com/krlvm/AccentColorizer/assets/51774833/0c67a2b0-280b-4311-8157-6c03e70fa1b6)

**Comment by Vipin2003** [comment]
But I talked to SAB with this and he said that it can be colorized. He also did in SAB on my opinion.

**Comment by krlvm** [comment]
SAB also hooks Explorer to achieve that
