### ISSUE TITLE
Some Little but important Improvements to AccentColorizer

### ISSUE THREAD

**Issue by Vipin2003** [krlvm/AccentColorizer#34]
1. Is it possible to colorize the Shortcut arrow and Compressed icon?? I think that it is a bitmap.

![2023-05-18_21h52_17](https://github.com/krlvm/AccentColorizer/assets/93650504/83284ae3-bf5b-4209-a801-9cedeed1e82b)

![2023-05-18_21h54_49](https://github.com/krlvm/AccentColorizer/assets/93650504/677fe0da-cc57-4d2a-99d7-371717e188d5)

2. The outline of a buttons should also be Colorized.
![2023-05-18_22h01_36](https://github.com/krlvm/AccentColorizer/assets/93650504/5cd5d530-5689-4158-9777-e5f09a6e8fcb)

3. Hovering over any file / folder should not be Blue. It should change color like it changes after selecting a file.
![2023-05-18_22h08_56](https://github.com/krlvm/AccentColorizer/assets/93650504/b786923e-cad2-4594-97c7-75f9f9d32f17)

**SOME OF THEM ARE ADOPTED BY STARTALLBACK BUT NOT YET AC**

**Comment by krlvm** [comment]
№1 Can't be colorized without hard-patching DLL with icons

As for the rest ([and this screenshot from your other issue](https://github.com/krlvm/AccentColorizer/issues/33#issuecomment-1553470105)) - those elements are colorized, it's just a glitch, restart your computer and run AccentColorizer again.
