### ISSUE TITLE
What is the diffrence between  Installer.zip Static.exe and .exe?

### ISSUE THREAD

**Issue by sevelee** [krlvm/AccentColorizer#39]
![image](https://github.com/krlvm/AccentColorizer/assets/8036235/f74fb476-5960-4087-96cf-a5c1e5239301)

**Comment by krlvm** [comment]
Static builds does not require Visual C++ Redistributable to be installed

**Comment by sevelee** [comment]
Sorry, but I have another question. How to uninstall AccentColorizer? Or it doesn't need uninstall just restart the computer? I used `AccentColorizer-Static-x64.exe`.

**Comment by krlvm** [comment]
There's an uninstaller in the archive

**Comment by krlvm** [comment]
If you want to uninstall manually, just stop the process, remove the executable and remove the startup entry from registry.
