### ISSUE TITLE
No Wiki, no UI and nothing happened upon execution.

### ISSUE THREAD

**Issue by sillyjaybird** [krlvm/AccentColorizer#44]
I tried running AccentColorizer on Windows 11 latest build and it did absolutely nothing. There was no UI and the only thing I could see in was that Task Manager showed it running and apparently running at every startup. I also didn't see any way to uninstall it. Any help would be appreciated.

**Comment by krlvm** [comment]
That's right, it is absolutely minimal and has no UI or preferences. It will automatically adjust colors to match your system-wide preference.
To uninstall it, run corresponding batch file from the distribution archive.

**Comment by sillyjaybird** [comment]
@krlvm Thanks. I now realize that I executed AccentColorizer-E11. Does the AccentColorizer uninstall cmd work for AC-E11?

**Comment by krlvm** [comment]
No, but there's also no installer distributed with AC-E11. It's enough to kill its process.
