### ISSUE TITLE
Compiling AccentColorizer

### ISSUE THREAD

**Issue by WinExperiments** [krlvm/AccentColorizer#48]
What do I need to compile AccentColorizer properly? When I do it with VS 2022 (with the component packs of desktop C++, desktop .NET, and UWP), the compiled program colorizes very few elements (system colors, checkboxes, and radio buttons only.)

**Comment by krlvm** [comment]
What does the compilation have to do with it? Something is wrong with your theme.

**Comment by WinExperiments** [comment]
Tried now with the Microsoft theme and more elements are colorized (despite remaining blue when I use my theme). Is it because my theme has some desaturated images that AccentColorizer attempts to colorize but fails and thus, not colorizing the rest of the elements?

**Comment by WinExperiments** [comment]
I actually solved it just by replacing TMT_DIBDATA with 0 in the problematic elements.
