### ISSUE TITLE
Functionality broken on latest dev build 25151.1000

### ISSUE THREAD

**Issue by ashergz** [krlvm/AccentColorizer#8]
As you can see, default blue line under textbox
![image](https://user-images.githubusercontent.com/35883201/176916280-83d8168d-5580-4b0e-b760-d29f0555e4f7.png)

**Comment by krlvm** [comment]
Most likely AccentColorizer just hung at a certain stage, try killing it in the task manager and starting it again

**Comment by ashergz** [comment]
Oh shit that worked. Thanks!

**Comment by Dhyfer1** [comment]
What did you do to make the Run dialog box look like that?

**Comment by ashergz** [comment]
Micaforeveryone

**Comment by Dhyfer1** [comment]
ok. Thanks!
